on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Build and Publish website
jobs:
  Build-And-Deploy:
    name: Build-And-Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
        env:
          VITE_GAPI_KEY: ${{ secrets.REACT_APP_GAPI_KEY }}
          VITE_REACT_APP_GAPI_CLINET_ID: ${{ secrets.REACT_APP_REACT_APP_GAPI_CLINET_ID }}
          VITE_ANALYTICS_GTAG_ID: ${{ secrets.REACT_APP_ANALYTICS_GTAG_ID }}
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
